const LABELS = {
  ADD_NEW_WALLET: 'Add New Wallet',
  WALLET_NAME: "Wallet Name",
  WALLET_ADDRESS: "Wallet Address",
  CANCEL: "Cancel",
  SAVE: "Save",
  RESET: "Reset",
  DELETE: "Delete",
  SEARCH: "Search",
  CLOSE: "Close",
  PLATINUM: "Platinum",
  GOLD: "Gold",
  RED: "Red",
  BLUE: "Blue",
  YELLOW: "Yellow",
  GREEN: "Green",
  REFLECTIONS: "Reflections",
  EDIT_REFLECTIONS: "Edit Reflections",
  EDIT_STAKING_REFLECTIONS: "Edit Staking Reflections",
  STAKED: "Staked",
  REWARDS_FROM: "Rewards From",
  EDIT_WALLET: "Edit Wallet",
  SETTINGS: "Settings",
  THEME: "Theme",
  LANGUAGE: "Language",
  SINCE: "Since",
  POOL_SHARE: "Pool Share",
  UNCLAIMED: "Unclaimed",
  COPY_NOTICE: "Wallet address copied to clipboard",
  WALLET_DESIGN: "Wallet Design",
}

export {LABELS};
