const LABELS = {
  ADD_NEW_WALLET: "Ajouter un nouveau portefeuille",
  WALLET_NAME: "Nom du portefeuille",
  WALLET_ADDRESS: "Adresse du portefeuille",
  CANCEL: "Annuler",
  SAVE: "Sauvegarder",
  RESET: "Réinitialiser",
  DELETE: "Supprimer",
  SEARCH: "Rechercher",
  CLOSE: "Fermer",
  PLATINUM: "Platinum",
  GOLD: "Or",
  RED: "Rouge",
  BLUE: "Bleu",
  YELLOW: "Jaune",
  GREEN: "Vert",
  REFLECTIONS: "Reflections",
  EDIT_REFLECTIONS: "Éditer les reflections",
  EDIT_STAKING_REFLECTIONS: "Éditer les reflections du stacking",
  STAKED: "Staked",
  REWARDS_FROM: "Récompense de",
  EDIT_WALLET: "Éditer le portefeuille",
  SETTINGS: "Settings",
  THEME: "Theme",
  LANGUAGE: "Language",
  POOL_SHARE: "Pool Share",
  UNCLAIMED: "Unclaimed",
  COPY_NOTICE: "Wallet address copied to clipboard",
  WALLET_DESIGN: "Wallet Design",
}

export {LABELS};
